package com.procurement.email.model;

import jakarta.persistence.*;
import lombok.Data;
import java.time.LocalDateTime;

/**
 * Entity representing a Request for Requisition (RRF) document.
 * Generated via LLM based on procurement request details.
 */
@Entity
@Table(name = "request_for_requisition")
@Data
public class RequestForRequisition {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    @Column(name = "po_number", unique = true, nullable = false)
    private String poNumber;
    
    @Column(name = "requester_email")
    private String requesterEmail;
    
    @Column(name = "requester_name")
    private String requesterName;
    
    @Column(name = "item_name")
    private String itemName;
    
    @Column(name = "item_type")
    private String itemType;
    
    @Column(name = "quantity")
    private Integer quantity;
    
    @Column(name = "estimated_amount")
    private java.math.BigDecimal estimatedAmount;
    
    @Column(name = "rrf_content", columnDefinition = "TEXT")
    private String rrfContent; // The formatted RRF document generated by LLM
    
    @Column(name = "specifications", columnDefinition = "TEXT")
    private String specifications; // JSON string of specifications
    
    @Column(name = "justification", columnDefinition = "TEXT")
    private String justification; // Business justification
    
    @Column(name = "additional_notes", columnDefinition = "TEXT")
    private String additionalNotes;
    
    @Column(name = "status")
    private String status; // DRAFT, PENDING_APPROVAL, APPROVED, REJECTED
    
    @Column(name = "created_at")
    private LocalDateTime createdAt;
    
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;
    
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }
    
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
